package org.opensha.oaf.util;

import java.io.OutputStream;
import java.io.PrintStream;

// The following code was generated by Copilot.

/**
 * AutoOutNull temporarily silences System.out and System.err using separate sinks.
 *
 * <p>Usage:
 * <pre>{@code
 * try (AutoOutNull ignored = new AutoOutNull()) {
 *     System.out.println("Discarded.");
 *     System.err.println("Also discarded, via a separate sink.");
 * }
 * // Restored after close:
 * System.out.println("Visible again.");
 * }</pre>
 */
public final class AutoOutNull implements AutoCloseable {

	private final PrintStream previousOut;
	private final PrintStream previousErr;

	// Separate PrintStreams that discard all output.
	private final PrintStream nullOutPrintStream;
	private final PrintStream nullErrPrintStream;

	private boolean closed = false;

	/**
	 * Constructs an AutoOutNull that replaces System.out and System.err with
	 * separate PrintStreams that discard all output, while remembering the originals.
	 */
	public AutoOutNull() {
		this.previousOut = System.out;
		this.previousErr = System.err;

		// Null output stream that ignores all data written to it.
		OutputStream nullOut = new OutputStream() {
			@Override
			public void write(int b) { /* discard */ }
			@Override
			public void write(byte[] b, int off, int len) { /* discard */ }
			@Override
			public void flush() { /* no-op */ }
		};

		// Separate null stream for err (kept distinct from out).
		OutputStream nullErr = new OutputStream() {
			@Override
			public void write(int b) { /* discard */ }
			@Override
			public void write(byte[] b, int off, int len) { /* discard */ }
			@Override
			public void flush() { /* no-op */ }
		};

		this.nullOutPrintStream = new PrintStream(nullOut, /* autoFlush */ false);
		this.nullErrPrintStream = new PrintStream(nullErr, /* autoFlush */ false);

		System.setOut(this.nullOutPrintStream);
		System.setErr(this.nullErrPrintStream);
	}

	/**
	 * Restores the original System.out and System.err.
	 * This method is idempotent; calling it multiple times is safe.
	 */
	@Override
	public void close() {
		if (closed) {
			return;
		}
		System.setOut(previousOut);
		System.setErr(previousErr);

		// Close both sinks.
		nullOutPrintStream.close();
		nullErrPrintStream.close();

		closed = true;
	}

}