package org.opensha.oaf.util.catalog;


// Generate event IDs.
// Author: Michael Barall 10/29/2021.
//
// This is a mechanism to generate event IDs, for use in producing simulated
// catalogs, and for adding event IDs to catalogs where the original IDs were
// removed.  It can also recognize IDs it produced.
//
// Within a given run of the program, this produces a different ID each time
// it is called.  However, currently, different runs produce the same IDs.
//
// The class is synchronized to allow use from multiple threads.

public class EventIDGenerator {

	// Event counter.

	private static long event_counter = 10000000L;


	// String that is used as a prefix, chosen to be unlikely to conflict with any Comcat ID.

	private static final String GEN_ID_PREFIX = "__G_";


	// Generate a new ID.

	public static synchronized String generate_id () {
		return GEN_ID_PREFIX + (++event_counter);
	}


	// Return true if the id was generated by this class.

	public static boolean is_generated_id (String id) {
		return id.startsWith (GEN_ID_PREFIX);
	}

}
